# Generated by Django 2.1.7 on 2019-05-01 02:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('type', models.CharField(choices=[('01', 'ลากิจ'), ('02', 'ลาป่วย')], max_length=2)),
                ('date_start', models.DateField()),
                ('date_end', models.DateField()),
                ('approve_status', models.IntegerField(choices=[(0, 'ไม่อนุมัติ'), (1, 'อนุมัติ'), (2, 'รอการอนุมัติ')], default=2)),
                ('created_by', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
